spring:
  application:
    name: spring-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql:
        dialect: org.hibernate.dialect.MySQLDialect
  server:
    port: 8080
jwt:
  validity:
    accessToken: 86400000
    refreshToken: 2592000000
  secret: jwt-secret-codeasdfghjkl;